name: my_movie_list
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  # Service locator
  get_it: ^6.1.1
  # Bloc for state management
  flutter_bloc: ^7.0.0
  # Value equality
  equatable: ^2.0.0
  # Functional programming thingies
  dartz: 0.10.0-nullsafety.1
  # Remote API
  data_connection_checker: ^0.3.4
  http: ^0.13.1
  # Local cache
  shared_preferences: ^2.0.5

  cached_network_image: ^2.5.0
  flutter_swiper: ^1.1.6
  percent_indicator: ^3.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.16.0
  bloc_test: ^8.0.0
  mockito: ^4.1.1

flutter:
  uses-material-design: true
